version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: 
      dockerfile: Dockerfile
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
  fhir-data-loader:
    build:
      dockerfile: Pythondockerfile
    depends_on:
      hapi-fhir-jpaserver-start:
        condition: service_started

    command: sh -c "sleep 180 && python ./fhir_data_loader.py"  
    ports:
      - "8090:8090"
    
volumes:
  hapi-fhir-postgres:
